import type { ImageSource } from 'expo-image';
import type { ArtworkKey } from '../../../packages/home-scene/src/cinematicArtwork';

/** Static requires keep every card image bundled, offline, and independent of external image services. */
export const cinematicArtworkAssets: Record<ArtworkKey, ImageSource> = {
  'room-living': require('../../../assets/cinematic/room-living.jpg'),
  'room-kitchen': require('../../../assets/cinematic/room-kitchen.jpg'),
  'room-bedroom': require('../../../assets/cinematic/room-bedroom.jpg'),
  'room-bathroom': require('../../../assets/cinematic/room-bathroom.jpg'),
  'room-family': require('../../../assets/cinematic/room-family.jpg'),
  'room-laundry': require('../../../assets/cinematic/room-laundry.jpg'),
  'room-gym': require('../../../assets/cinematic/room-gym.jpg'),
  'room-grounds': require('../../../assets/cinematic/room-grounds.jpg'),
  'room-utility': require('../../../assets/cinematic/room-utility.jpg'),
  'mood-morning': require('../../../assets/cinematic/mood-morning.jpg'),
  'mood-night': require('../../../assets/cinematic/mood-night.jpg'),
  'mood-movie': require('../../../assets/cinematic/mood-movie.jpg'),
  'mood-away': require('../../../assets/cinematic/mood-away.jpg'),
  'device-light': require('../../../assets/cinematic/device-light.jpg'),
  'device-lamp': require('../../../assets/cinematic/device-lamp.jpg'),
  'device-fan': require('../../../assets/cinematic/device-fan.jpg'),
  'device-tv': require('../../../assets/cinematic/device-tv.jpg'),
  'device-washer': require('../../../assets/cinematic/device-washer.jpg'),
  'device-ac': require('../../../assets/cinematic/device-ac.jpg'),
  'device-blinds': require('../../../assets/cinematic/device-blinds.jpg'),
  'device-gate': require('../../../assets/cinematic/device-gate.jpg'),
  'device-smoke': require('../../../assets/cinematic/device-smoke.jpg'),
  'device-air': require('../../../assets/cinematic/device-air.jpg'),
  'device-speaker': require('../../../assets/cinematic/device-speaker.jpg'),
  'device-vacuum': require('../../../assets/cinematic/device-vacuum.jpg'),
  'device-door': require('../../../assets/cinematic/device-door.jpg'),
  'device-fridge': require('../../../assets/cinematic/device-fridge.jpg'),
  'device-stove': require('../../../assets/cinematic/device-stove.jpg'),
  'device-coffee': require('../../../assets/cinematic/device-coffee.jpg'),
  'device-microwave': require('../../../assets/cinematic/device-microwave.jpg'),
  'device-dishwasher': require('../../../assets/cinematic/device-dishwasher.jpg'),
  'device-window': require('../../../assets/cinematic/device-window.jpg'),
  'device-dryer': require('../../../assets/cinematic/device-dryer.jpg'),
  'device-generator': require('../../../assets/cinematic/device-generator.jpg'),
  'device-battery': require('../../../assets/cinematic/device-battery.jpg'),
  'device-energy': require('../../../assets/cinematic/device-energy.jpg'),
  'device-solar': require('../../../assets/cinematic/device-solar.jpg'),
  'device-water': require('../../../assets/cinematic/device-water.jpg'),
  'device-water-heater': require('../../../assets/cinematic/device-water-heater.jpg'),
  'device-garage': require('../../../assets/cinematic/device-garage.jpg'),
  'device-camera': require('../../../assets/cinematic/device-camera.jpg'),
  'device-sprinkler': require('../../../assets/cinematic/device-sprinkler.jpg'),
  'device-gas-meter': require('../../../assets/cinematic/device-gas-meter.jpg'),
  'device-gas-leak': require('../../../assets/cinematic/device-gas-leak.jpg'),
  'device-street-light': require('../../../assets/cinematic/device-street-light.jpg'),
  'device-ventilation': require('../../../assets/cinematic/device-ventilation.jpg'),
  'device-generic': require('../../../assets/cinematic/device-generic.jpg'),
};
