persistence true
persistence_location /mosquitto/data
log_dest stdout

include_dir /mosquitto/config/conf.d
listener 1883 0.0.0.0
listener 9001 0.0.0.0
protocol websockets
allow_anonymous false
password_file /mosquitto/config/passwords
acl_file /mosquitto/config/acl
