import { StyleSheet } from "react-native";
import { theme } from "../../theme/theme";

/** Shared structure for the profile's focused forms and household detail sheets. */
export const householdStyles = StyleSheet.create({
  fill: { flex: 1, minHeight: 0 },
  body: {
    flex: 1,
    minHeight: 0,
    gap: 14,
    width: "100%",
    maxWidth: 880,
    alignSelf: "center",
  },
  stack: { gap: 14 },
  formContent: { gap: 16, paddingBottom: 8 },
  section: { gap: 12 },
  header: { flexDirection: "row", alignItems: "center", gap: 12 },
  heading: { flex: 1, minWidth: 0, gap: 4 },
  eyebrow: {
    color: theme.colors.accentText,
    fontSize: 10,
    fontWeight: "600",
    letterSpacing: 2,
  },
  title: {
    color: theme.colors.text,
    fontSize: 23,
    lineHeight: 29,
    fontWeight: "500",
  },
  subtitle: { color: theme.colors.subtext, fontSize: 13, lineHeight: 19 },
  label: { color: theme.colors.subtext, fontSize: 12, fontWeight: "500" },
  inputGroup: { gap: 7 },
  input: {
    minHeight: 48,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
    backgroundColor: theme.colors.card2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.stroke,
    color: theme.colors.text,
    fontSize: 15,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    minHeight: 54,
  },
  rowDivider: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.stroke,
    paddingBottom: 10,
  },
  rowText: { color: theme.colors.text, fontSize: 14, fontWeight: "500" },
  detail: { color: theme.colors.subtext, fontSize: 12, lineHeight: 18 },
  actions: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 10,
  },
  footer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 10,
    paddingTop: 4,
  },
  choices: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  choice: {
    minHeight: 44,
    minWidth: 70,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: theme.colors.stroke,
    borderRadius: 14,
    backgroundColor: theme.colors.card2,
  },
  choiceSelected: {
    backgroundColor: theme.colors.bg1,
    borderColor: theme.colors.accent,
  },
  choiceText: { color: theme.colors.subtext, fontSize: 12, fontWeight: "500" },
  choiceTextSelected: { color: theme.colors.accentText },
  disabled: { opacity: 0.45 },
  avatar: { alignItems: "center", gap: 14, paddingVertical: 12 },
  avatarRing: {
    padding: 9,
    borderWidth: 1,
    borderColor: theme.colors.accent,
    borderRadius: 70,
    backgroundColor: theme.colors.card2,
  },
  swatches: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 8,
  },
  swatch: {
    width: 44,
    height: 44,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "transparent",
  },
  swatchSelected: { borderColor: theme.colors.text },
  violet: { backgroundColor: "#B46BFF" },
  purple: { backgroundColor: "#7A5CFF" },
  rose: { backgroundColor: "#FF9AA2" },
  blue: { backgroundColor: "#A0E9FF" },
  gold: { backgroundColor: "#FFD166" },
  green: { backgroundColor: "#A5FF9B" },
  memberIdentity: { alignItems: "center", gap: 12, paddingVertical: 14 },
  memberName: {
    color: theme.colors.text,
    fontSize: 24,
    fontWeight: "500",
    textAlign: "center",
  },
  memberMeta: {
    color: theme.colors.accentText,
    fontSize: 13,
    textAlign: "center",
  },
  memberActions: { gap: 10 },
  memberAction: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 58,
    paddingHorizontal: 14,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.stroke,
    backgroundColor: theme.colors.card2,
    gap: 12,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    backgroundColor: theme.colors.card2,
  },
  badgeLabel: {
    color: theme.colors.accentText,
    fontSize: 11,
    fontWeight: "500",
  },
  danger: { color: "#FFD0DE" },
  dangerAction: {
    minHeight: 44,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.stroke,
    paddingHorizontal: 14,
  },
  sheet: {
    alignSelf: "center",
    width: "100%",
    maxWidth: 580,
    maxHeight: "92%",
    borderRadius: 26,
    padding: 20,
    gap: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.stroke,
  },
  sheetScroll: { flexShrink: 1 },
  serviceIcon: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: theme.colors.card2,
  },
  empty: {
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingVertical: 32,
  },
});
