import { StyleSheet } from 'react-native';
import { theme } from '../../theme/theme';

/** Keep personal controls bounded on phones while sharing the account sheet's visual language. */
export const accountPreferencesStyles = StyleSheet.create({
  overlay: { flex: 1, padding: 12, backgroundColor: theme.colors.overlayStrong, alignItems: 'center', justifyContent: 'flex-end' },
  tabletOverlay: { alignItems: 'flex-end', justifyContent: 'flex-start', padding: 20 },
  panel: { width: '100%', maxWidth: 440, maxHeight: '100%', borderRadius: 28, borderWidth: 1, borderColor: theme.colors.stroke },
  content: { flexShrink: 1, maxHeight: '100%' },
  heading: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 16, borderBottomWidth: 1, borderBottomColor: theme.colors.stroke },
  copy: { flex: 1, minWidth: 0, gap: 3 },
  eyebrow: { color: theme.colors.accentText, fontSize: 9, lineHeight: 12, letterSpacing: 1.2, fontWeight: '600' },
  title: { color: theme.colors.text, fontSize: 25, lineHeight: 30, fontWeight: '500', letterSpacing: -0.6 },
  iconButton: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, borderColor: theme.colors.stroke, alignItems: 'center', justifyContent: 'center' },
  tabs: { flexDirection: 'row', paddingHorizontal: 12, paddingTop: 12, gap: 4 },
  tab: { flex: 1, minHeight: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'transparent', paddingHorizontal: 4 },
  selectedTab: { borderColor: theme.colors.stroke, backgroundColor: theme.colors.card },
  tabText: { color: theme.colors.subtext, fontSize: 12, lineHeight: 18, fontWeight: '500' },
  selectedTabText: { color: theme.colors.text },
  body: { flexShrink: 1 },
  bodyContent: { padding: 16, gap: 12 },
  section: { gap: 10 },
  sectionTitle: { color: theme.colors.text, fontSize: 17, lineHeight: 23, fontWeight: '500' },
  detail: { color: theme.colors.subtext, fontSize: 12, lineHeight: 17 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 72, padding: 12, borderRadius: 18, backgroundColor: theme.colors.card2, borderWidth: 1, borderColor: theme.colors.stroke },
  rowTitle: { color: theme.colors.text, fontSize: 14, lineHeight: 20, fontWeight: '500' },
  toggle: { minWidth: 48, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  toggleTrack: { width: 44, height: 26, borderRadius: 13, padding: 3, backgroundColor: theme.colors.stroke },
  toggleTrackOn: { backgroundColor: theme.colors.accent2 },
  toggleThumb: { width: 20, height: 20, borderRadius: 10, backgroundColor: theme.colors.text },
  toggleThumbOn: { transform: [{ translateX: 18 }] },
  choices: { flexDirection: 'row', gap: 8 },
  choice: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', padding: 8, borderRadius: 15, borderWidth: 1, borderColor: theme.colors.stroke, backgroundColor: theme.colors.card2 },
  selectedChoice: { borderColor: theme.colors.accentText, backgroundColor: theme.colors.card },
  choiceText: { color: theme.colors.text, fontSize: 13, lineHeight: 20, fontWeight: '500' },
  action: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderRadius: 16, borderWidth: 1, borderColor: theme.colors.stroke, padding: 10 },
  actionText: { color: theme.colors.accentText, fontSize: 13, lineHeight: 18, fontWeight: '500' },
  notice: { padding: 12, borderRadius: 14, backgroundColor: theme.colors.card2 },
  footer: { minHeight: 38, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: 16, paddingBottom: 12 },
  footerText: { color: theme.colors.subtext, fontSize: 11, lineHeight: 16 },
  disabled: { opacity: 0.55 },
});
