import { StyleSheet } from 'react-native';
import { theme } from '../../theme/theme';

/** Shared layout for the arrival screen; decoration yields to short screens and large text. */
export const verificationStyles = StyleSheet.create({
  root: { ...StyleSheet.absoluteFillObject, backgroundColor: theme.colors.bg0 },
  fill: { flex: 1 },
  backdrop: { ...StyleSheet.absoluteFillObject },
  safeArea: { flex: 1 },
  scrollContent: { flexGrow: 1, paddingHorizontal: 28, paddingVertical: 24, alignItems: 'center' },
  scrollContentCompact: { paddingHorizontal: 24, paddingVertical: 14 },
  shell: { flexGrow: 1, width: '100%', maxWidth: 1120 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  brand: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  wordmark: { color: theme.colors.text, fontSize: 12, fontWeight: '700', letterSpacing: 2.8 },
  headerLabel: { color: theme.colors.accentText, fontSize: 9, fontWeight: '600', letterSpacing: 1.6 },
  main: { flexGrow: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: 24 },
  mainCompact: { paddingVertical: 14 },
  mainWide: { flexDirection: 'row', gap: 48, paddingHorizontal: 24 },
  visual: { width: '100%', maxWidth: 400, height: 310, justifyContent: 'center', alignItems: 'center', marginBottom: 10 },
  visualCompact: { height: 205, maxWidth: 300, marginBottom: 0 },
  visualSmall: { height: 88, maxWidth: 132 },
  visualWide: { flex: 1, height: 420, maxWidth: 480, marginBottom: 0 },
  narrative: { width: '100%', maxWidth: 420, alignItems: 'center' },
  narrativeWide: { flex: 1, alignItems: 'flex-start' },
  eyebrow: { color: theme.colors.accentText, fontSize: 10, fontWeight: '600', letterSpacing: 3, marginBottom: 12 },
  title: { color: theme.colors.text, fontSize: 43, lineHeight: 48, letterSpacing: -1.7, fontWeight: '300', textAlign: 'center', marginBottom: 24 },
  titleCompact: { fontSize: 34, lineHeight: 39, marginBottom: 18 },
  titleWide: { textAlign: 'left', fontSize: 48, lineHeight: 54, marginBottom: 28 },
  titleAccessible: { fontSize: 28, lineHeight: 34, marginBottom: 20 },
  statusCard: { width: '100%', borderWidth: 1, borderColor: theme.colors.stroke, borderRadius: theme.radius.lg, backgroundColor: theme.colors.card2, padding: 18, gap: 12, overflow: 'hidden' },
  statusCardCompact: { padding: 15, gap: 10 },
  statusRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  statusIcon: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.colors.card2, borderWidth: 1, borderColor: theme.colors.stroke },
  statusText: { flex: 1, gap: 4 },
  statusLabel: { color: theme.colors.accentText, fontSize: 8, fontWeight: '700', letterSpacing: 2 },
  statusLabelPaused: { color: theme.colors.ember },
  statusTitle: { color: theme.colors.text, fontSize: 15, lineHeight: 21, fontWeight: '500' },
  statusDescription: { color: theme.colors.subtext, fontSize: 12, lineHeight: 19 },
  hairline: { height: 1, width: '100%', backgroundColor: theme.colors.stroke },
  actions: { width: '100%', flexDirection: 'row', gap: 10, marginTop: 16 },
  actionsAccessible: { flexDirection: 'column' },
  button: { flex: 1, minHeight: 50, paddingHorizontal: 18, paddingVertical: 13, borderRadius: theme.radius.sm, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, borderWidth: 1, borderColor: theme.colors.stroke },
  buttonPrimary: { backgroundColor: theme.colors.accentText, borderColor: theme.colors.accentText },
  buttonSecondary: { backgroundColor: theme.colors.card2 },
  buttonText: { color: theme.colors.text, fontSize: 13, lineHeight: 19, fontWeight: '600', flexShrink: 1, textAlign: 'center' },
  buttonTextPrimary: { color: theme.colors.bg0 },
  disabled: { opacity: 0.5 },
  actionError: { color: theme.colors.ember, fontSize: 13, lineHeight: 20, marginTop: 14, width: '100%' },
  footer: { alignItems: 'center', gap: 12, paddingTop: 8 },
  footerRule: { width: 26, height: 1, backgroundColor: theme.colors.accent },
  footerText: { color: theme.colors.muted, fontSize: 10, lineHeight: 16, textAlign: 'center', letterSpacing: 0.25 },
});
