import { StyleSheet } from "react-native";
import { theme } from "../../theme/theme";

/** Shared room, search, and favorite layouts keep the device browser inside its measured viewport. */
export const deviceBrowserStyles = StyleSheet.create({
  compactResult: {
    flex: 1,
    minHeight: 88,
    flexDirection: "row",
    borderWidth: 1,
    borderColor: theme.colors.stroke,
    borderRadius: 18,
    backgroundColor: theme.colors.card2,
    overflow: "hidden",
  },
  compactIdentity: {
    flex: 1,
    minWidth: 0,
    padding: 12,
    justifyContent: "center",
    gap: 6,
  },
  compactName: {
    color: theme.colors.text,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  compactActions: {
    width: 44,
    borderLeftWidth: 1,
    borderColor: theme.colors.stroke,
  },
  compactAction: {
    minHeight: 44,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  disabled: { opacity: 0.4 },
  searchRow: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingLeft: 12,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: theme.colors.stroke,
    backgroundColor: theme.colors.card2,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    minHeight: 44,
    paddingVertical: 8,
    color: theme.colors.text,
    fontSize: 13,
  },
  clear: {
    width: 44,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  breadcrumb: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  contextValue: { color: theme.colors.text, fontSize: 12, flexShrink: 1 },
  filter: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "transparent",
  },
  selectedFilter: {
    backgroundColor: theme.colors.card2,
    borderColor: theme.colors.stroke,
  },
  backLabel: { color: theme.colors.accentText, fontSize: 12 },
  saveWarning: { color: theme.colors.subtext, fontSize: 11, lineHeight: 16 },
  empty: {
    flex: 1,
    minHeight: 0,
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 18,
  },
  emptyTitle: {
    color: theme.colors.text,
    fontSize: 18,
    fontWeight: "500",
    textAlign: "center",
  },
  emptyDetail: {
    color: theme.colors.subtext,
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
  cards: { flex: 1, minHeight: 0, gap: 10 },
  cardRow: { flex: 1, minHeight: 0, flexDirection: "row", gap: 10 },
  roomCard: {
    flex: 1,
    minWidth: 0,
    padding: 14,
    borderRadius: 22,
    backgroundColor: theme.colors.card,
    borderWidth: 1,
    borderColor: theme.colors.stroke,
    justifyContent: "space-between",
    gap: 8,
  },
  cardTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 6,
  },
  roomName: {
    color: theme.colors.text,
    fontSize: 18,
    fontWeight: "500",
    letterSpacing: -0.5,
  },
  roomDetail: { color: theme.colors.subtext, fontSize: 10, lineHeight: 15 },
  spacer: { flex: 1 },
});
