import { StyleSheet } from "react-native";
import { theme } from "../../theme/theme";

/** Luminous control panels and compact navigation keep every settings category in one viewport. */
export const settingsStyles = StyleSheet.create({
  root: { flex: 1, minHeight: 0 },
  standaloneHeader: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: theme.colors.stroke },
  standaloneTitle: { color: theme.colors.text, fontSize: 26, fontWeight: "500" },
  workspace: { flex: 1, minHeight: 0, padding: 20, gap: 20, width: "100%", maxWidth: 1100, alignSelf: "center" },
  compactWorkspace: { padding: 12, gap: 10 },
  wideWorkspace: { flexDirection: "row", padding: 28, gap: 36 },
  navigation: { flexDirection: "row", backgroundColor: theme.colors.card2, borderWidth: 1, borderColor: theme.colors.stroke, borderRadius: 20, padding: 4, gap: 2 },
  sideNavigation: { width: 176, flexDirection: "column", alignSelf: "flex-start", padding: 8, gap: 8 },
  category: { flex: 1, minWidth: 44, minHeight: 50, alignItems: "center", justifyContent: "center", gap: 4, borderRadius: 15 },
  sideCategory: { flex: 0, minHeight: 52, flexDirection: "row", justifyContent: "flex-start", gap: 12, paddingHorizontal: 4 },
  selectedCategory: { backgroundColor: theme.colors.accent2 },
  categoryLabel: { color: theme.colors.subtext, fontSize: 11, fontWeight: "500" },
  sideCategoryLabel: { fontSize: 14 },
  selectedLabel: { color: theme.colors.accent },
  panel: { flex: 1, minHeight: 0, gap: 18, justifyContent: "center", backgroundColor: theme.colors.glass, borderWidth: 1, borderColor: theme.colors.stroke, borderRadius: 28, padding: 24, overflow: "hidden" },
  compactPanel: { gap: 12, padding: 14, borderRadius: 24 },
  panelHeading: { gap: 7 },
  panelOrbit: { position: "absolute", right: -100, top: -110, width: 240, height: 240, borderRadius: 120, borderWidth: 1, borderColor: theme.colors.accent2, backgroundColor: theme.colors.glow, opacity: 0.14 },
  eyebrow: { color: theme.colors.accent, fontSize: 10, fontWeight: "600", letterSpacing: 2.2 },
  title: { color: theme.colors.text, fontSize: 30, lineHeight: 36, fontWeight: "500", letterSpacing: -0.8 },
  compactTitle: { fontSize: 25, lineHeight: 30 },
  description: { color: theme.colors.subtext, fontSize: 14, lineHeight: 21 },
  detail: { color: theme.colors.subtext, fontSize: 12, lineHeight: 18 },
  rows: { borderTopWidth: 1, borderTopColor: theme.colors.stroke },
  row: { minHeight: 48, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: theme.colors.stroke, gap: 16, paddingVertical: 10 },
  label: { color: theme.colors.subtext, fontSize: 13, flexShrink: 0 },
  value: { flexShrink: 1, color: theme.colors.text, fontSize: 14, textAlign: "right", lineHeight: 20 },
  homeName: { color: theme.colors.text, fontSize: 18, fontWeight: "500", lineHeight: 24 },
  actions: { flexDirection: "row", gap: 12, flexWrap: "wrap" },
  action: { minHeight: 48, minWidth: 44, flexGrow: 1, flexBasis: 120, paddingHorizontal: 14, paddingVertical: 10, borderWidth: 1, borderColor: theme.colors.stroke, borderRadius: 16, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  primaryAction: { backgroundColor: theme.colors.accent, borderColor: theme.colors.accent, shadowColor: theme.colors.accent, shadowOpacity: 0.12, shadowRadius: 14, shadowOffset: { width: 0, height: 4 } },
  actionLabel: { color: theme.colors.text, fontSize: 13, fontWeight: "600", textAlign: "center", flexShrink: 1 },
  primaryActionLabel: { color: theme.colors.bg0 },
  disabled: { opacity: 0.5 },
  inputGroup: { gap: 8 },
  input: { minHeight: 48, paddingHorizontal: 12, paddingVertical: 10, color: theme.colors.text, fontSize: 14, borderWidth: 1, borderColor: theme.colors.stroke, borderRadius: 16 },
  subpageNavigation: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8, borderTopWidth: 1, borderTopColor: theme.colors.stroke, paddingTop: 6 },
  pagerButton: { minHeight: 44, minWidth: 44, justifyContent: "center", alignItems: "center" },
  pageLabel: { color: theme.colors.subtext, fontSize: 12 },
  notice: { borderLeftWidth: 2, borderLeftColor: theme.colors.accent, paddingLeft: 12, paddingVertical: 4 },
});
