import { StyleSheet } from "react-native";

/** Shared comparison-screen colors keep both renderers inside the same quiet frame. */
export const labColors = {
  background: "#101f1d",
  panel: "#192d29",
  raised: "#243a34",
  stroke: "#354b43",
  text: "#f3f0e7",
  muted: "#b4c3b8",
  sage: "#d2e7bb",
  ink: "#1a2c23",
};

/** Fixed control heights preserve the scene's space without adding a vertical scroll view. */
export const labStyles = StyleSheet.create({
  root: { flex: 1, minHeight: 0, backgroundColor: labColors.background, padding: 12, gap: 10 },
  toolbar: { flexDirection: "row", alignItems: "center", gap: 10 },
  brand: { flex: 1, gap: 2 },
  eyebrow: { fontSize: 10, fontWeight: "700", letterSpacing: 1.4, color: labColors.sage },
  title: { fontSize: 19, fontWeight: "600", color: labColors.text },
  segmented: { flexDirection: "row", padding: 3, gap: 3, borderRadius: 15, backgroundColor: labColors.panel },
  segment: { minHeight: 44, minWidth: 64, alignItems: "center", justifyContent: "center", paddingHorizontal: 12, borderRadius: 12 },
  segmentSelected: { backgroundColor: labColors.sage },
  segmentDisabled: { opacity: 0.45 },
  segmentText: { fontSize: 12, fontWeight: "600", color: labColors.muted },
  segmentSelectedText: { color: labColors.ink },
  body: { flex: 1, minHeight: 0, gap: 10 },
  bodyLandscape: { flexDirection: "row" },
  sceneColumn: { flex: 1, minHeight: 0, gap: 8 },
  scene: { flex: 1, minHeight: 100, borderRadius: 22, overflow: "hidden", backgroundColor: "#263931" },
  sceneOverlay: { ...StyleSheet.absoluteFillObject, alignItems: "center", justifyContent: "center", padding: 24, backgroundColor: "rgba(16,31,29,0.90)", gap: 12 },
  overlayTitle: { color: labColors.text, fontSize: 17, fontWeight: "600", textAlign: "center" },
  overlayBody: { color: labColors.muted, fontSize: 12, lineHeight: 18, textAlign: "center", maxWidth: 260 },
  overlayActions: { flexDirection: "row", flexWrap: "wrap", gap: 8, justifyContent: "center" },
  button: { minHeight: 44, paddingHorizontal: 14, borderRadius: 12, backgroundColor: labColors.raised, justifyContent: "center", alignItems: "center" },
  buttonPrimary: { backgroundColor: labColors.sage },
  buttonText: { color: labColors.text, fontSize: 12, fontWeight: "600" },
  buttonPrimaryText: { color: labColors.ink },
  metrics: { flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 2 },
  metric: { flex: 1, gap: 2 },
  metricValue: { color: labColors.text, fontSize: 14, fontVariant: ["tabular-nums"], fontWeight: "600" },
  metricLabel: { color: labColors.muted, fontSize: 9, letterSpacing: 0.5 },
  footnote: { fontSize: 10, lineHeight: 14, color: labColors.muted },
  panel: { backgroundColor: labColors.panel, borderRadius: 20, padding: 10, gap: 8 },
  panelLandscape: { width: 260, alignSelf: "stretch", justifyContent: "space-between" },
  panelSection: { gap: 8 },
  row: { flexDirection: "row", alignItems: "center", gap: 6 },
  grow: { flex: 1 },
  smallButton: { flex: 1, minHeight: 44, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: labColors.raised, paddingHorizontal: 6 },
  smallButtonActive: { backgroundColor: labColors.sage },
  deviceRow: { flexDirection: "row", gap: 8 },
  device: { flex: 1, backgroundColor: labColors.raised, borderRadius: 13, borderWidth: 1, borderColor: "transparent", overflow: "hidden" },
  deviceSelected: { borderColor: labColors.sage },
  deviceToggle: { minHeight: 44, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 6 },
  deviceName: { color: labColors.text, fontSize: 12, fontWeight: "600" },
  deviceState: { color: labColors.sage, fontSize: 11, fontWeight: "600" },
  deviceDetails: { minHeight: 44, justifyContent: "center", paddingHorizontal: 10, borderTopWidth: 1, borderTopColor: labColors.stroke },
  deviceDetailsText: { color: labColors.muted, fontSize: 11 },
  detail: { minHeight: 70, gap: 4, justifyContent: "center", paddingHorizontal: 3 },
  detailHeading: { color: labColors.text, fontSize: 12, fontWeight: "600" },
  detailValue: { color: labColors.sage, fontSize: 12, fontVariant: ["tabular-nums"] },
  slider: { width: "100%", height: 44 },
  detailDescription: { color: labColors.muted, fontSize: 11, lineHeight: 16 },
  pressFeedback: { opacity: 0.72 },
});
