import { StyleSheet } from "react-native";
import { theme } from "../../theme/theme";

/** Keep the room index bounded and room editing on one deliberate detail surface. */
export const roomWorkspaceStyles = StyleSheet.create({
  fill: { flex: 1, minHeight: 0 },
  overview: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
  },
  overviewText: { gap: 5, flex: 1 },
  eyebrow: {
    color: theme.colors.accentText,
    fontSize: 10,
    letterSpacing: 1.8,
    fontWeight: "600",
  },
  title: { color: theme.colors.text, fontSize: 23, fontWeight: "500" },
  detail: { color: theme.colors.subtext, fontSize: 12, lineHeight: 18 },
  summary: {
    color: theme.colors.text,
    fontSize: 15,
    fontWeight: "500",
    paddingHorizontal: 2,
  },
  search: {
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: theme.colors.card2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.stroke,
    paddingHorizontal: 15,
    paddingVertical: 10,
    color: theme.colors.text,
    fontSize: 14,
  },
  grid: { flex: 1, minHeight: 0, gap: 10 },
  gridWide: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignContent: "flex-start",
  },
  card: {
    minHeight: 94,
    borderRadius: 23,
    backgroundColor: theme.colors.card2,
    borderWidth: 1,
    borderColor: theme.colors.stroke,
    flexDirection: "row",
    alignItems: "center",
    overflow: "hidden",
  },
  cardWide: { width: "48.9%", minHeight: 148 },
  openRoom: {
    flex: 1,
    minWidth: 0,
    minHeight: 94,
    alignSelf: "stretch",
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    gap: 10,
  },
  manageRoom: {
    minWidth: 62,
    minHeight: 54,
    gap: 4,
    marginRight: 8,
    paddingHorizontal: 5,
    alignItems: "center",
    justifyContent: "center",
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: theme.colors.stroke,
  },
  manageLabel: {
    color: theme.colors.text,
    fontSize: 11,
    fontWeight: "500",
  },
  icon: {
    width: 40,
    height: 40,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.colors.card,
  },
  roomText: { flex: 1, minWidth: 0, gap: 6 },
  roomName: {
    color: theme.colors.text,
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "500",
  },
  cardDetail: { color: theme.colors.text },
  cardLabelShadow: { textShadowColor: "rgba(20,18,26,0.85)", textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 3 },
  empty: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12 },
  sheet: {
    width: "100%",
    maxWidth: 540,
    alignSelf: "center",
    borderRadius: 26,
    padding: 22,
    borderWidth: 1,
    borderColor: theme.colors.stroke,
    gap: 18,
  },
  section: { gap: 10 },
  label: { color: theme.colors.subtext, fontSize: 12, fontWeight: "500" },
  actions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    alignItems: "center",
  },
  footer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "flex-end",
    paddingTop: 8,
  },
  danger: {
    minHeight: 44,
    justifyContent: "center",
    paddingHorizontal: 14,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: theme.colors.stroke,
  },
  dangerText: { color: "#FFD0DE", fontSize: 13, fontWeight: "500" },
  disabled: { opacity: 0.4 },
});
