-- Sprint 2: distributed Edge Function rate buckets. Identifiers are HMAC
-- hashes generated by the Edge runtime; raw client IPs are never stored.

create schema if not exists private;

create table if not exists private.edge_rate_limit_buckets (
  endpoint text not null,
  key_hash text not null check (key_hash ~ '^[0-9a-f]{64}$'),
  window_started_at timestamptz not null,
  request_count integer not null check (request_count > 0),
  updated_at timestamptz not null default now(),
  primary key (endpoint, key_hash, window_started_at)
);

create index if not exists edge_rate_limit_buckets_window_idx
  on private.edge_rate_limit_buckets(window_started_at);

revoke all on schema private from public, anon, authenticated;
revoke all on private.edge_rate_limit_buckets from public, anon, authenticated;

create or replace function consume_edge_rate_limit(
  limit_endpoint text,
  limit_key_hash text,
  limit_max_requests integer,
  limit_window_seconds integer
)
returns table(allowed boolean, remaining integer, retry_after_seconds integer)
language plpgsql
security definer
set search_path = public, private
as $$
declare
  current_epoch bigint := floor(extract(epoch from clock_timestamp()));
  bucket_start_epoch bigint;
  bucket_start timestamptz;
  next_count integer;
begin
  if limit_endpoint !~ '^[a-z0-9][a-z0-9._-]{0,63}$'
     or limit_key_hash !~ '^[0-9a-f]{64}$'
     or limit_max_requests not between 1 and 10000
     or limit_window_seconds not between 1 and 86400 then
    raise exception 'Invalid edge rate-limit policy';
  end if;

  bucket_start_epoch := current_epoch - (current_epoch % limit_window_seconds);
  bucket_start := to_timestamp(bucket_start_epoch);

  insert into private.edge_rate_limit_buckets(
    endpoint, key_hash, window_started_at, request_count
  ) values (
    limit_endpoint, limit_key_hash, bucket_start, 1
  )
  on conflict (endpoint, key_hash, window_started_at)
  do update set
    request_count = private.edge_rate_limit_buckets.request_count + 1,
    updated_at = clock_timestamp()
  returning request_count into next_count;

  -- Opportunistic bounded retention keeps this security table from growing
  -- indefinitely without requiring another service or a Docker-side process.
  if random() < 0.01 then
    delete from private.edge_rate_limit_buckets
    where window_started_at < clock_timestamp() - interval '24 hours';
  end if;

  return query select
    next_count <= limit_max_requests,
    greatest(limit_max_requests - next_count, 0),
    case
      when next_count <= limit_max_requests then 0
      else greatest(
        bucket_start_epoch + limit_window_seconds - current_epoch,
        1
      )::integer
    end;
end;
$$;

revoke all on function consume_edge_rate_limit(text, text, integer, integer)
  from public, anon, authenticated;
grant execute on function consume_edge_rate_limit(text, text, integer, integer)
  to service_role;
